### ISSUE TITLE
send fax using ARI

### ISSUE THREAD

**Issue by JobExpert** [skrusty/AsterNET.ARI#1]
Hi,

i tried to send fax using AsterNET.ARI without any success.
Can we SendFax using AsterNET.ARI?
if yes how we do it?

**Comment by JobExpert** [comment]
I tried to call SendFAX Application using ARI:
Channel channel = ARIClient.Channels.Originate("local/" + outgoingFaxNumber + "@from-internal",
                                     null,
                                     null,
                                     null,
                                     "SendFAX",
                                     "{Tiff file path as param}",
                                     extentionToUse.TrimStart(new Char[] { '0' }));
            ARIClient.Applications.Subscribe(_FAX_SERVER_APP, "channel:" + channel.Id);

I was getting "unknown SendFAX stasis application" message in asterisk log.

i ended with the following solution:
Channel channel = ARIClient.Channels.OriginateWithId(actionStatusLog.UniqueId,
                                    "local/" + outgoingFaxNumber + "@from-internal",
                                     "s",
                                     "from-internal-fax",
                                     1,
                                     null,
                                     null,
                                     extentionToUse.TrimStart(new Char[] { '0' }));
ARIClient.Applications.Subscribe(_FAX_SERVER_APP, "channel:" + channel.Id);

i define "from-internal-fax" as context in extensions_custom.conf:
[from-internal-fax]
exten => s,1,Set(FAXOPT(filename)=/var/spool/asterisk/tmp/${UNIQUEID}.tiff)                 
exten => s,n,Set(FAXOPT(ecm)=yes)
exten => s,n,Set(FAXOPT(headerinfo)=Fax Machine)
exten => s,n,Set(FAXOPT(localstationid)=123456789)
exten => s,n,Set(FAXOPT(maxrate)=14400)
exten => s,n,Set(FAXOPT(minrate)=9600)
exten => s,n,SendFAX(/var/spool/asterisk/tmp/${UNIQUEID}.tiff,f)
exten => h,1,NoOp(FAXOPT(ecm) : ${FAXOPT(ecm)})
exten => h,n,NoOp(FaxStatus : ${FAXSTATUS})
exten => h,n,NoOp(FaxStatusString : ${FAXSTATUSSTRING})
exten => h,n,NoOp(FaxError : ${FAXERROR})
exten => h,n,NoOp(RemoteStationID : ${REMOTESTATIONID})
exten => h,n,NoOp(FaxPages : ${FAXPAGES})
exten => h,n,NoOp(FaxBitRate : ${FAXBITRATE})
exten => h,n,NoOp(FaxResolution : ${FAXRESOLUTION})
; end of from-internal-fax context

i use ARIClient.Channels.OriginateWithId instedof ARIClient.Channels.Originate because i didn't get the List<KeyValuePair<string, string>> variables param in from-internal-fax context.

i have few question:
1) why i didn't get the List<KeyValuePair<string, string>> variables in from-internal-fax context?
2) i'm using Asterisk 12 can we get "ManagerEvent_FAXStatus" in ARI?
3) do you have any suggestion/improvement?

Thanks in advanced.

**Comment by skrusty** [comment]
the issue here is originate in ari is not the same as in ami or agi. ari does not allow dialplan applications to be executed.

originate only allows ari applications to be connected to the new channel. However, you can call dialplan functions be setting them like a variable, like in my simpleconf example, where I start speaker detection. Check that out, if fax supports dialplan functions that might be easier.

**Comment by skrusty** [comment]
Here is an example of calling a dialplan function using SetChannelVar to turn on Speaker Detection.

```c#
// Turn on talk detection on this channel
_client.Channels.SetChannelVar(c.Id, "TALK_DETECT(set)", "");
```

**Comment by skrusty** [comment]
closing due to no reply

**Comment by JobExpert** [comment]
Hi,

Sorry for late response.
10x for your help.

I ended up with the following solution:

-Added new Context in asterisk server:
Edit this file /etc/asterisk/extensions_custom.conf and add:
        [from-internal-fax]
        exten => s,1,Set(FAXOPT(filename)=${FAX_APP_FILE_PATH})                 
        exten => s,n,Set(FAXOPT(ecm)=yes)
        exten => s,n,Set(FAXOPT(headerinfo)=${FAX_APP_HEADER_INFO})
        exten => s,n,Set(FAXOPT(localstationid)=${FAX_APP_LOCAL_STATION_ID})
        exten => s,n,Set(FAXOPT(maxrate)=14400)
        exten => s,n,Set(FAXOPT(minrate)=9600)
        exten => s,n,SendFAX(${FAX_APP_FILE_PATH},f)
        exten => h,1,NoOp(FAXOPT(ecm) : ${FAXOPT(ecm)})
        exten => h,n,NoOp(FaxStatus : ${FAXSTATUS})
        exten => h,n,NoOp(FaxStatusString : ${FAXSTATUSSTRING})
        exten => h,n,NoOp(FaxError : ${FAXERROR})
        exten => h,n,NoOp(RemoteStationID : ${REMOTESTATIONID})
        exten => h,n,NoOp(FaxPages : ${FAXPAGES})
        exten => h,n,NoOp(FaxBitRate : ${FAXBITRATE})
        exten => h,n,NoOp(FaxResolution : ${FAXRESOLUTION})
        ; end of from-internal-fax context

Define the following consts:
const String _FAX_SERVER_APP = "FaxApp";
        const String _FROM_INTERNAL_FAX_CONTEXT = "from-internal-fax";
        const String _FAX_APP_FILE_PATH = "FAX_APP_FILE_PATH";
        const String _FAX_APP_HEADER_INFO = "FAX_APP_HEADER_INFO";
        const String _FAX_APP_LOCAL_STATION_ID = "FAX_APP_LOCAL_STATION_ID";

Implement the stasis event:
private static void _AriClient_OnStasisStartEvent(object sender, StasisStartEvent e)
        {           
            try
            {
                if (e.Application == _FAX_SERVER_APP)
                {
                    _AriClient.Channels.SetChannelVar(e.Channel.Id, _FAX_APP_FILE_PATH, e.Args[0]);
                    _AriClient.Channels.SetChannelVar(e.Channel.Id, _FAX_APP_HEADER_INFO, "some header info");                    
                    _AriClient.Channels.SetChannelVar(e.Channel.Id, _FAX_APP_LOCAL_STATION_ID, e.Args[1]);

                    _AriClient.Channels.ContinueInDialplan(e.Channel.Id, _FROM_INTERNAL_FAX_CONTEXT, "s", 1);
                }
            }
            catch (Exception ex)
            {
                LogManager.GetLogger(EMAIL_LOGGER).Error(ex);
            }            
        }

Create channel and send fax:
Channel channel = ARIClient.Channels.OriginateWithId("GUID",
                                        String.Format("SIP/{0}/{1}",
                                                    SIPServer.TrunkName,
                                                    faxSessionLine.FaxSession.OutgoingFaxNumber),
                                         null,
                                         null,
                                         null,
                                         _FAX_SERVER_APP,
                                         TiffFilePath + ",{our fax phone number}",
                                         extentionToUse.TrimStart(new Char[] { '0' }));
