### ISSUE TITLE
Event ordering is not guaranteed.

### ISSUE THREAD

**Issue by pragmatrix** [skrusty/AsterNET.ARI#11]
Hi, I noticed that even though the events received from Asterisk do have an ordering guarantee (it's a concern in their design, for example see the fixed bugs [here](https://reviewboard.asterisk.org/r/2419/) and [here](https://reviewboard.asterisk.org/r/4163/)), the ordering is not guaranteed in the AriClient, because it dispatches the received events to the thread pool with [`Delegate.BeginInvoke()`](https://github.com/skrusty/AsterNET.ARI/blob/master/AsterNET.ARI/ARIClient.cs#L158).

One example is that a hangup event always must come before the stasis end event, and I can imagine other related issues, like the playback started and finished event, though I do not have much experience with ARI so far.

The WebSocket implementation does seem to guarantee the ordering, because there is always the .NET socket's IOCompletionCallback on the stack that is delivering the socket's data.

I don't see an elegant solution to this problem based on the current event handler based design of the AriClient. The only solution I can think of would be to provide a SynchronizationContext of a dedicated thread to dispatch the events to.

One alternative I can think of would require the following changes:

- AriClient only maintains one properly ordered queue of events, probably including the connection state events.
- Events can be dynamically dispatched to an object that implements interfaces of the particular method groups (channel, bridge, etc.). This way, clients can use the current thread or power up their own, then pull out one event after another from AriClient and dispatch the events to their object that implements their state machine.

**Comment by skrusty** [comment]
I like the idea of a plugable event dispatcher. It would offer the most flexible solution. Open to suggestions of course.

**Comment by pragmatrix** [comment]
Well, I think that depends on the programming model AriClient wants to support. 

As long the task parallel library is not supported, I personally prefer a synchronous and blocking API that never leaves the calling thread even when it calls back through events. For example, I would implement the `Connect()` as a synchronous method with a CancellationToken parameter and also support explicit reconnects through another call to `Connect()` or `Reconnect()` method that also blocks as long the WebSocket's state is `Connecting` or throws an exception if the connection attempt fails.

Regarding the event dispatching, I would also like to see a synchronous method like `GetNextEvent()` that returns the next available event or blocks until an event is available and returns it. the event dispatching could then be completely externalized as an extension method to `Event`, so that client code looks similar:

```c#
using (var connection = ariClient.Connect(cancellationToken))
{
  var myStateMachine = new StateMachine(connection /* required to call the action methods*/);

  while (var event = connection.GetNextEvent(cancellationToken))
  {
    event.DispatchTo(myStateMachine);
  }
}
```

If a connection gets lost, I would prefer an exception to be thrown, and so it is in the client's hand to decide if to reconnect or actually end the application. As long the `connection` instance is not disposed, event queuing should run all the time, so that no event is lost when a reconnect completes and `GetNextEvent()` is called again.

This would simplify development to a great degree. Inside of `StateMachine` no thread synchronization is required, and if a state machine is not appropriate, the client code could be structured around sequential calls to `GetNextEvent()`.

**Comment by skrusty** [comment]
You should join me and the others in #asternet on irc (freenode). Would be good to chat more about our ideas and those some of the others have based on reading this.

**Comment by skrusty** [comment]
Getting ready to merge this change this week.
