### ISSUE TITLE
More a question that an issue

### ISSUE THREAD

**Issue by danradic-lateral** [skrusty/AsterNET.ARI#15]
Hi Ben,

As I said in my email, I'm trying to create a conference app using your AsterNet.ARI project, but I have some unclarities/difficulties.
We have an external Asterisk server upgraded to version 13 to support the RESTful interface.
I've put the server/conference details into the app and it successfully connects: "Connection state is now true".

Q: It's not clear for me how can I create a dialplan application and test the app by dialing a number from my phone and receiving some kind of response, using AsterNet.ARI?

Thanks
Dan

**Comment by skrusty** [comment]
You can use the exmaples in the headers of the samples. For example

```
 * Extensions.conf exmaple setup
 * 
 *   exten => 7001,1,Noop()
 *   same => n,Stasis(simpleconf,test)
 *   same => n,hangup()
```

**Comment by skrusty** [comment]
closed due to inactivity
