### ISSUE TITLE
Code Generation should work out of the box.

### ISSUE THREAD

**Issue by pragmatrix** [skrusty/AsterNET.ARI#16]
Regenerating the code for the ARI Events and Actions does not work out of the box. Here are some issues I had:

- at  https://github.com/skrusty/AsterNET.ARI/blob/master/CodeGeneratror/ARICodeGen/Templates/Models.tt#L23 there is an absolute file path that points to the json definition files. I think this should be changed to @"..\Data\"
- When I run the code generator inside Visual Studio 2015, I get some excessive newlines, for example between every param line. 

I needed to change:

```
#>
		/// <param name="<#= param.SelectToken("name").Value<string>() #>"><#= param.SelectToken("description").Value<string>() #></param>
<#
```

into

```
#>		/// <param name="<#= param.SelectToken("name").Value<string>() #>"><#= param.SelectToken("description").Value<string>() #></param>
<#
```

to avoid two newlines (one before the param line, and the one after). 

- I think that the date in the header comment should be removed as long the code files are checked in to the repository, so that merge conflicts can be avoided.
- In VS2015, the files are generated in a subdirectory `Templates`. It is not clear how these files should be distributed / copied back into the Asternet.ARI project in the directory structure below `ARI_1_0`. A script would be nice, or some kind of post build process in the code generation step.
- The generated code uses tabs, but the rest of the code uses spaces.

**Comment by skrusty** [comment]
I'd like to get the code to be moved by the t4 generator into the main ARI project. It's possible, but I couldn't get it working.

**Comment by skrusty** [comment]
If anyone knows how to do this, that would be a great contrib!
