### ISSUE TITLE
Code Generation puts IEndpointsActions methods SendMessage and SendMessageToEndpoint into comments :)

### ISSUE THREAD

**Issue by pragmatrix** [skrusty/AsterNET.ARI#17]
The following lines:

https://github.com/skrusty/AsterNET.ARI/blob/master/AsterNET.ARI/ARI_1_0/Actions/IEndpointsActions.cs#L25

https://github.com/skrusty/AsterNET.ARI/blob/master/AsterNET.ARI/ARI_1_0/Actions/IEndpointsActions.cs#L44

https://github.com/skrusty/AsterNET.ARI/blob/master/AsterNET.ARI/ARI_1_0/Actions/EndpointsActions.cs#L46

https://github.com/skrusty/AsterNET.ARI/blob/master/AsterNET.ARI/ARI_1_0/Actions/EndpointsActions.cs#L135

do not look right. I think that there is a problem with the code generator.

**Comment by skrusty** [comment]
Yeah, i spotted this too, had to manually fix it in my last run of the code generator.

**Comment by skrusty** [comment]
This has been resolved in current source branch Master.
#29
