### ISSUE TITLE
403 Authentication Issue

### ISSUE THREAD

**Issue by danradic-lateral** [skrusty/AsterNET.ARI#19]
Hi, 

I'm getting the " The remote server returned an error: (403) Forbidden." WebException in the RestActionConsumer. Any idea how to overcome this ?

Thanks.

    public IRestCommandResult<T> ProcessRestCommand<T>(IRestCommand command) where T : new()
        {
            var cmd = (Command) command;
            var result = cmd.Client.Execute<T>(cmd.Request); //here is where the exception occurs

            var rtn = new CommandResult<T> {StatusCode = result.StatusCode, Data = result.Data};

            return rtn;
        }

**Comment by skrusty** [comment]
Have you confirmed the username and password you're providing are correct?

Maybe goto http://air.asterisk.org, put your asterisk details into the host box and the username and password into the authentication box (format user:pass ) and test you can connect ok.

**Comment by danradic-lateral** [comment]
SwaggerUI says: "Can't read from server. It may not have the appropriate access-control-origin settings."

But my username and password must be correct, tested it directly into the browser's address bar getting the response in json format, also the app's console says: "Connection state is now true".

Does this have something to do with enabling CORS?

**Comment by skrusty** [comment]
might be...
```
;allowed_origins =	; Comma separated list of allowed origins, for
;			; Cross-Origin Resource Sharing. May be set to * to
;			; allow all origins.
```

Are you connecting to Asterisk from a remote host? Not able to check my own setup at the moment for the allowed_origins, but worth a shot!

**Comment by danradic-lateral** [comment]
Yes I'm connecting from a remote host.
These settings are in ari.conf file?
Should be: 

    allowed_origins = * ; Comma separated list of allowed origins, for ... 

?

**Comment by danradic-lateral** [comment]
Will try this and get back when I get a response from the server guys.
Thanks

**Comment by danradic-lateral** [comment]
Hi, do you maybe have an example setting of the allowed_origins config?

**Comment by skrusty** [comment]
Not to hand. Might be best to ask on asterisk mailing list. Sorry.

**Comment by danradic-lateral** [comment]
OK, will do that, thanks :)
