### ISSUE TITLE
SimpleConf: Multiple conferences management

### ISSUE THREAD

**Issue by dna55** [skrusty/AsterNET.ARI#23]
Hi,

In my app a user can set up a conference by completing a form in the web app UI which inserts the conference details into the local DB, like auto-incremented integers as conference Id's, callerId, Pin, startTime etc...

The SimpleConf Conference constructor has a Guid Id parameter that is generated on the spot each time a bridge is created?

My question is how can I link my set conference to the Stasis conference and add a caller into the correct conference in case of multiple conferences in the same time? 

Thanks.
Dan

**Comment by skrusty** [comment]
If you're using SimpleConf then you send a caller to a conference by passing the conference name in Stasis as follows:

```same => n,Stasis(simpleconf,test)```

where 'test' is the conference name.

**Comment by dna55** [comment]
Does that require a new StasisEndpoint for each conference?

```
Client = new AriClient(new StasisEndpoint(AppConfig.ServerIP, AppConfig.Port, AppConfig.UserName, AppConfig.UserPassword), AppConfig.AppName);
Conference.Conferences.Add(new Conference(Client, Guid.NewGuid(), AppConfig.ConferenceName));
```

From my understanding a Bridge has a 1:1 relationship with a conference and a Channel has a 1:1 relationship with a caller. If that is correct, there should be a new bridge created for every conference?

`Bridge bridge = _client.Bridges.Create("mixing", Id.ToString(), ConferenceName);`

**Comment by skrusty** [comment]
No, when you call that dialplan function (stasis) you're passing in the application name and a parameter. The param is the conference name. That tells the sample which conference to put the caller in.

**Comment by skrusty** [comment]
You need to add the code that creates the other conferences, it's just a sample!
