### ISSUE TITLE
How to solve Web4Socket  Issue ?

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET.ARI#24]
Error Message "**Could not load file or assembly 'WebSocket4Net, Version=0.14.1.0, Culture=neutral, PublicKeyToken=eb4e154b696bf72a' or one of its dependencies. The system cannot find the file specified**"

**Comment by skrusty** [comment]
You need to have WebSocket4Net in your project too? How did you get AsterNET.ARI? Using the release or via NuGET?

You're better off using NuGET.
https://www.nuget.org/packages/AsterNET.ARI/

**Comment by k07** [comment]
Thanks ...Issue solved..

**Comment by Lesliehdezg** [comment]
i need delete WebSocket4Net for this solution with NuGET?
