### ISSUE TITLE
Adding custom headers to channel

### ISSUE THREAD

**Issue by chasik** [skrusty/AsterNET.ARI#26]
When using OriginateWithId method, I pass the parameter variables as described in the article (["ARI Originate and SIP Headers"](http://www.xdev.net/2015/10/16/ari-originate-and-sip-headers)). 
In my case this dictionary: 
```
new Dictionary<string, string>() 
{ {"SIPADDHEADER0", "custom-header-1:custom-value-1"}, {"SIPADDHEADER1", "custom-header-2:custom-value-2"} } 
```
JsonConvert serializes this into the format: 
`{"custom-header-1":"custom-value-1", "custom-header-2":"custom-value-2"}`
But this format is not suitable, as documentation Asterisk ARI said: 

> The' variables ' key in the body object holds variable key/value pairs to set on the channel on creation. Other keys in the object body are interpreted as query parameters. Ex. { "endpoint": "SIP/Alice", "variables": { "CALLERID(name)": "Alice" } }

Necessary in the methods Originate and OriginateWithId instead of Dictionary<string, string> apply Dictionary<string, object> for serialize nested objects... How could have stated the problem, maybe there is a more rational decision... Please give me an example. Thank you.

**Comment by skrusty** [comment]
What version of AsterNET.ARI are you using please? There was a problem in an older version that might have caused something like that.

**Comment by skrusty** [comment]
I build headers like so:

```c#
variables = new Dictionary <string, string>();
var counter = 0;
foreach (var h in _headers)
{
    variables.Add($"SIPADDHEADER{counter}", h);
    counter++;
}
```
where h is a string something like "headername: value"
then
```c#
 _client.Channels.OriginateWithId(
                    ChannelId,
                    "SIP/foo",
                    app: _ariAppName,
                    timeout: _timeout,
                    callerId: _callerId,
                    variables: variables);
```

**Comment by chasik** [comment]
I downloaded from Nuget - version 1.1.0 - the last, as I understand it. After reading the article to clone the repository - the result is the same. The file has a title:
/ * 
AsterNET ARI Framework Automatically generated file @ 12/10/2015 11:53:27
* /
Asterisk version - tried as 12 and 13 (the latest version).
In our case, when serializing the dictionary we get a string without a key "variables" - a set of data transmitted in a dictionary of key/value (which is logical). If you use swager - online service at asterisk.org - there need to just format {"variable" : {"key1:val1", "key2:val2", "key3:val3"}}, but it passed only {"key1:val1", "key2:val2", "key3:val3"} and header not set (sorry my English). I add one row in method AddParametr (Command.cs):
```
        public void AddParameter(string name, object value, Middleware.ParameterType type)
        {
            if (type == ParameterType.RequestBody)
            {
                Request.RequestFormat = DataFormat.Json;

               ** var mbaSetValuesDict = new Dictionary<string, object> { { "variables", value } };
**
                Request.AddParameter(name,** JsonConvert.SerializeObject(mbaSetValuesDict), **(RestSharp.ParameterType)Enum.Parse(typeof(RestSharp.ParameterType), type.ToString()));
            }
            else
            {
                Request.AddParameter(name, value, (RestSharp.ParameterType)Enum.Parse(typeof(RestSharp.ParameterType), type.ToString()));
            }
        }
```
and all work good for my case... I do not want to go into the source code - I want to be updated with no problems .... Sorry, please ...
