### ISSUE TITLE
No support for subscribeAll parameter for /events websocket resource

### ISSUE THREAD

**Issue by andrey-prokopyev** [skrusty/AsterNET.ARI#33]

**Comment by skrusty** [comment]
Hey, great contrib thanks. I will look over and review this today.

**Comment by andrey-prokopyev** [comment]
Hi @skrusty! How is review going?

**Comment by chasik** [comment]
Очень нужно!

**Comment by tpatata2010** [comment]
Realy, if a solution is found post it please!

**Comment by skrusty** [comment]
Merged into master branch
