### ISSUE TITLE
Pass data from exteernal Stasis app to DialPlan

### ISSUE THREAD

**Issue by SueSingh** [skrusty/AsterNET.ARI#45]
Hi,

I need to know if there's a way to pass data from an external Stasis app to a Dialplan. I'm using ...channel/<channelid>/continue

Scenario:
- call from outside world is directed to an extension and dialplan in Asterisk
- Dialplan Answers and places the channel into an external stasisapp
- Stasis app performs some functionality then sends the channel back to dialplan 
(...channel/<channelid>/continue)

`exten => 1001,1,NoOp(entering ${CONTEXT} as defined in extensions_custom.conf)
same => n,Answer()
same => n,Stasis(ZIN1,arg1)
same => n,Hangup()
`

The data I wish to pass the dialplan could be char or numeric.

Thank you

**Comment by maximguskov** [comment]
Hi.
You can use post var in channel https://wiki.asterisk.org/wiki/display/AST/Asterisk+15+Channels+REST+API#Asterisk15ChannelsRESTAPI-setChannelVar

**Comment by SueSingh** [comment]
Thank you kindly. That's perfect.
