### ISSUE TITLE
Channel Not In Stasis Application

### ISSUE THREAD

**Issue by CShelton11** [skrusty/AsterNET.ARI#52]
What am I missing here?  Application always says -- **Channel Not In Stasis Application**

Here are the basics in my test:

DialerClient = new AriClient(new StasisEndpoint(endpoint, Convert.ToInt32(port), username, password), application);
DialerClient.Connect();
DialerClient.OnConnectionStateChanged += OnStateEvent;
DialerClient.OnStasisStartEvent += OnStartEvent;
DialerClient.OnStasisEndEvent += OnEndEvent;

** Events not shows

This is where it breaks:

var x = DialerClient.Channels.Originate("SIP/4193@IP.ETC", extension: "1000", app: application);
GlobalDialer.DialerClient.Channels.Ring(x.Id); **-- Breaks here / With any event really**

The channel is created, but when I look at the channel ids in the DialerClient there are none.
I thought that this was supposed to create the channel an register it in Stasis.
It never shows in Stasis.  What could be going wrong?
What do I need to do to get the channel in the Stasis application?
Is the dial plan absolutely required?  
If not can someone give me some example code for how it could be accomplished?

Thanks

Chris

**Comment by 91Abdullah** [comment]
1. Yes you need to do this in your asterisk application server.
2. This means that whenever an incoming call comes on number 1000 it will be put into stasis application. If you want to put an outbound channel into stasis application you need to put this in your outbound context.

**Comment by SueSingh** [comment]
static void Main()
{
    AriClient ActionClient = new AriClient(new StasisEndpoint("<IP>, 8088, "<username>", "<password>"), StasisAppName);

    ActionClient.OnStasisStartEvent += c_OnStasisStartEvent;
    ActionClient.OnStasisEndEvent += c_OnStasisEndEvent;
    ActionClient.OnChannelDtmfReceivedEvent += ActionClientOnChannelDtmfReceivedEvent;

    ActionClient.Connect();
    Bridge SimpleBridge = ActionClient.Bridges.Create("mixing", Guid.NewGuid().ToString(), StasisAppName); 

    ActionClient.Applications.Subscribe(StasisAppName, "bridge:" + SimpleBridge.Id);
    Channel ch1 = ActionClient.Channels.Originate(strEndPoint1, null, null, null, null, StasisAppName);
    Channel ch2 = ActionClient.Channels.Originate(strEndPoint2, null, null, null, null, StasisAppName);
}
 static void c_OnStasisStartEvent(object sender, AsterNET.ARI.Models.StasisStartEvent e)
{
            // Answer channel
            ActionClient.Channels.Answer(e.Channel.Id);
        
            // Add channel to bridge
            ActionClient.Bridges.AddChannel(SimpleBridge.Id, e.Channel.Id, "participant");
}

**Comment by CShelton11** [comment]
Thanks for the code sample!  I tried what you have provided but the OnStasisStartEvent is never fired.  Probably the reason the channel isn't in stasis...  Any ideas on why the event wouldn't fire?

**Comment by SueSingh** [comment]
If you're testing the above with a Console App, include a while-loop after above code. 
This allows your app to remain running, whilst you wait for events.
Example:
```
var done = false;
                while (!done)
                {
                    var lastKey = Console.ReadKey();
                    switch (lastKey.KeyChar.ToString())
                    {
                        case "*":
                            done = true;
                            break;
                        case "1":
                            ActionClient.Bridges.StopMoh(SimpleBridge.Id);
                            break;
                        case "2":
                            ActionClient.Bridges.StartMoh(SimpleBridge.Id, "default");
                            break;
                        case "3":
                            // Mute all channels on bridge
                            var bridgeMute = ActionClient.Bridges.Get(SimpleBridge.Id);
                            foreach (var chan in bridgeMute.Channels)
                                ActionClient.Channels.Mute(chan, "in");
                            break;
                    }
                }
```


Step 1: Connect to Asterisk server
Step 2: Set up event handlers and subscribe to stasisApp
Step 3: Originate(endpoint, ...., stasisApp)
Step 4: Have a message loop (or similar) waiting for events on this channel.

Hope this helps.
Sue

**Comment by SueSingh** [comment]
One more thing...Don't forget to Answer(...) you channel on your StasisStart Event.

```
static void c_OnStasisStartEvent(object sender, AsterNET.ARI.Models.StasisStartEvent e)
        {
            try
            {
                // Answer channel
                ActionClient.Channels.Answer(e.Channel.Id);

                // Add channel to bridge
                ActionClient.Bridges.AddChannel(SimpleBridge.Id, e.Channel.Id, "participant"); // "member"

                // Unmute channel
                ActionClient.Channels.Unmute(e.Channel.Id, "in");
                ActionClient.Channels.Unmute(e.Channel.Id, "out");
                ActionClient.Channels.StopSilence(e.Channel.Id);
                //ActionClient.Bridges.StartMoh(SimpleBridge.Id, "default");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                Console.ReadKey();
            }
        }
```

**Comment by CShelton11** [comment]
Appreciate the help, but the while loop looks like its really designed for prompts.  Why would I need this to actually make an outgoing phone call.  It just doesn't make sense to me.  If I want the application to dial person A, dial person B, and then connect the 2 people, this wouldn't really be relevant would it?  I am testing through an API project not a console application.  The follow is the full code snippet that I have thus far:

using AsterNET.ARI;
using AsterNET.ARI.Models;
using Company.Dialer.Services.Models;
using Microsoft.AspNet.OData;
using Microsoft.AspNet.OData.Routing;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Company.Dialer.Services.Controllers
{
    [ODataRoutePrefix("Tests")]
    public class TestController : ODataController
    {
        private static AriClient DialerClient;
        private static String DialerAddress;
        private static String DialerPort;
        private static String DialerApplication;
        private static Bridge DialerBridge;

        [ODataRoute]
        [EnableQuery]
        public IQueryable<Test> Get()
        {
            var application = ConfigurationManager.AppSettings["DialerApplication"].ToString();
            var address = ConfigurationManager.AppSettings["DialerAddress"].ToString();
            var port = ConfigurationManager.AppSettings["DialerPort"].ToString();
            var username = ConfigurationManager.AppSettings["DialerUsername"].ToString();
            var password = ConfigurationManager.AppSettings["DialerPassword"].ToString();
            var bridge = Guid.NewGuid().ToString();

            DialerClient = new AriClient(new StasisEndpoint(address, Convert.ToInt32(port), username, password), application);
            DialerAddress = address;
            DialerPort = port;
            DialerApplication = application;

            DialerClient.OnStasisStartEvent += OnStartEvent;
            DialerClient.OnStasisEndEvent += OnEndEvent;
            DialerClient.Applications.Subscribe(application, "bridge:" + bridge);
            DialerClient.Connect();


            DialerBridge = DialerClient.Bridges.Create("mixing", bridge, application);
            Channel ch1 = DialerClient.Channels.Originate("SIP/1000", null, null, null, null, application);
            Channel ch2 = DialerClient.Channels.Originate("SIP/1000", null, null, null, null, application);

            **// This is the part that is not clear the me.
            // How do I instruct the application to call an internal number on ch1
            // How do I instruct the application to call an external number on ch2
            // How do I tell the bridge to connect the 2 calls
            // The OnStartEvent events is never fired with this code, so I'm guessing there's a big piece 
            // that I'm missing
            // As it stands, the above code effectively doesn't do anything**

            var i = 0;
            while(i < 30)
            {
                System.Threading.Thread.Sleep(1000);
                i += 1;
            }

            DialerClient.Bridges.Destroy(bridge);

            // return list length 0
            return (new List<Test>()).AsQueryable();
        }

        static void OnStartEvent(object sender, AsterNET.ARI.Models.StasisStartEvent e)
        {
            DialerClient.Channels.Answer(e.Channel.Id);
            DialerClient.Bridges.AddChannel(DialerBridge.Id, e.Channel.Id, "participant");
        }

        public static void OnEndEvent(IAriClient sender, StasisEndEvent e)
        {
            DialerClient.Channels.Hangup(e.Channel.Id, "normal");
        }

    }

    

}

**Comment by CShelton11** [comment]
Got it to work!!!!  Your code was fine, but the issue was that the endpoints were not entered correctly.  Was able to get the calls connected using endpoint: Local/phonenumber@from-internal.  voila.  Thanks for all the help.

**Comment by SueSingh** [comment]
Hi,
Glad you got it to work.

I did not have a copy of your code, so I assumed you did not cater for the fact that the REST API is asynchronous, which means, that after you make a call to Asterisk, you need to wait for it to return (in a while-loop). However, I see that you did have a while-loop (my loop was merely an example to show you that it is waiting for events, rather than exiting the app).

You have not included error handling in your code, which is probably why you did not know that the Originate command was failing due to incorrect Endpoint configuration. When the Endpoint is incorrectly configured, Originate throws an exception. You are only supposed to enter the while-loop if Originate succeeds. If Originate fails, then you are waiting for no reason. Exit the program and assess you errors. Either use a console app, to write errors to the console, or a log file and write your errors there. You MUST check all returns from Asternet.ARI and wrap the code within try-catches to detect any failures.
