### ISSUE TITLE
how can i edit conf file with asternet.ari ?

### ISSUE THREAD

**Issue by safakseyrek** [skrusty/AsterNET.ARI#59]
how can i edit conf file with asternet.ari ?

ex;
sip.conf
extensions.conf

I couldn't see it in the documentation.

**Comment by skrusty** [comment]
You can't. You'll need to use the AMI framework for that (See AsterNET.AMI Framework)

**Comment by safakseyrek** [comment]
thanks for your answer. 
What can i do with asterisk.ARI basically?
Can you give an example?

**Comment by skrusty** [comment]
It's a call flow framework,. you can control calls within Asterisk, much like you could with a native .c application inside Asterisk.
