### ISSUE TITLE
The Middleware esposes only two states of the wbsocket connection

### ISSUE THREAD

**Issue by claudiuolteanu** [skrusty/AsterNET.ARI#6]
Hi there,

I was wondering why did you encapsulate the websocket connection states and why did you expose only two of them (**Open** and **Closed**) ? This can lead to some problems if someone wants to force socket's reconnection. 

For example: if I want to use the autoreconnect feature and also to expose to the end user the possibility to manually reconnect the socket, then you can have an inconsintent state. If the state of the websocket is **Connecting** and the user tries to manually reconnect it, it will raise a **WebSocket** exception. (*"The socket is connecting, cannot connect again!"*).

Thanks,
Claudiu

**Comment by skrusty** [comment]
Hi Claudio, to be honest mostly an oversight on my part and by no means by design. When creating the middlware my goal was primarily the introduction of the Queue middlware which doesn't need a connection state.

Suggestions always welcomed and I can see a benefit in exposing the Connecting state!
