### ISSUE TITLE
Consistantly get a 404 not found error when answering a channel

### ISSUE THREAD

**Issue by shawty** [skrusty/AsterNET.ARI#63]
Any app compiled and run directly on the asterisk server, or remotely in visual studio, generates a 404 exception and aborts in the start event handler.

OS: Ubuntu 16.04.6 LTS
Mem: 2gb
Disk +20Gb free
Running in a VM on HyperV with 2 virtualised CPU Cores

Dotnet Info
![image](https://user-images.githubusercontent.com/1876454/58705229-7ad37900-83a6-11e9-9369-ac392e73cb4c.png)

CS Code is the test app sample available from this Repo

Build output
![image](https://user-images.githubusercontent.com/1876454/58705298-a7879080-83a6-11e9-9cc7-dbf8e97e0dd8.png)

Asterisk Version: 
![image](https://user-images.githubusercontent.com/1876454/58705342-d1d94e00-83a6-11e9-9f8b-001065b96136.png)

Extension Setup:
![image](https://user-images.githubusercontent.com/1876454/58705493-53c97700-83a7-11e9-9ed0-53b08520867e.png)

ARI Setup:
![image](https://user-images.githubusercontent.com/1876454/58705556-79ef1700-83a7-11e9-86ed-42f0d847f6e3.png)

Asterix HTTP setup:
![image](https://user-images.githubusercontent.com/1876454/58706041-d141b700-83a8-11e9-9442-2b86fbb7683b.png)

Runtime output from ARI app:
![image](https://user-images.githubusercontent.com/1876454/58705663-c4709380-83a7-11e9-8e0b-1a74d95130a2.png)

Same Occurs in VS2019 (On core versions 2.0/2.1/2.2/3.0)
![image](https://user-images.githubusercontent.com/1876454/58705791-2204e000-83a8-11e9-9236-834fbc87b0d7.png)

Wireshark Trace running while App test running shows:
![image](https://user-images.githubusercontent.com/1876454/58705906-727c3d80-83a8-11e9-9654-3f07e339c156.png)

This occurs no matter what code I write.  As soon as an Answer is executed, everything ends with that 404

**Comment by shawty** [comment]
Update, heres the initial APP connection to Asterisk as seen in wire shark

![image](https://user-images.githubusercontent.com/1876454/58706961-62199200-83ab-11e9-8158-d62b793b3699.png)

![image](https://user-images.githubusercontent.com/1876454/58707028-9b520200-83ab-11e9-9ada-f4b986afc8f1.png)

**Comment by shawty** [comment]
Update 2, Finally found the start JSON sent to the app

![image](https://user-images.githubusercontent.com/1876454/58707673-80808d00-83ad-11e9-9f2b-aa199fa39efc.png)

Channel numbers etc appear to match.

**Comment by shawty** [comment]
Closing this issue.

I've built a new Asterisk install using Asterisk 13.17 (This issue was seen under 13.01) running on Ubuntu 18.04 (Report was on 16.04) ans all samples tested, from here and of own making work as expected and do not show 404 exceptions.

My conclusion is that there is either a bug in the previous Asterisk builds (Which I can find no trace of) or my configuration is some how broken on the previous build.

I ruled AsterNET out of the equation, by using a simple WebSocket connector plugin and a copy of "RestER" for firefox.  I was able to reproduce by connecting the web socket tester to Asterisk using the same URL as AsterNET uses, then when the dial came in from the softphone, used RestER to POST to the Asterisk Rest endpoint, with the same details as traced in wireshark.

This test yielded the same results, telling me that AsterNET was not the culprit here.

**Comment by skrusty** [comment]
@shawty Thank you for the detailed information. Glad to hear you were able to resolve the issue, and sorry none of us spotted this before you did.

**Comment by shawty** [comment]
No worries Ben, I know how these things go :-)  I have issues on some of my stuff that took me a year or more before I spotted it.

You might still want to investigate this though, on the back of what I encountered I also did a clean build on Unbuntu 16.04 (Asterisk 13.01) and again as per my report above, I encountered the same failiure, which leads me to believe that something may have changed between Ast 13.01 and 13.28 (13.28 being the build that ships with Ubuntu 18.04)

If I did anything else up I'll let you know.

Once I finish this book on dotnet core I'm on with for Packt, and once I get through the bit's I still need to write for Syncfusion, I intend doing a series of .net related posts on telephony and .net on my own blog, in about 3 months time I would think, hence why I started to explore this.

PS: I'm an ex GSM/Networks engineer for a what was a large Telco in the UK so this kind of stuff interests me :-)

**Comment by skrusty** [comment]
Cool, I need to give this project some attention again soon anyway. It needs a rebuild of the templates for a newer version of asterisk, quite a few API features missing.

Look forwards to any further feedback!

**Comment by shawty** [comment]
Well I'm sure I can help with exposure, and if time permits maybe even other parts of the project, documentation, samples etc.  No promises of course, time is usually the one thing I don't have enough of, but I help run one of the most prominent .NET developer groups on linked-in with over 50k members, and I'm a well known figure in the global .NET community, we should talk properly on skype or something at some time in the near future(ish) :-)
